### ISSUE TITLE
not issue but question.

### ISSUE THREAD

**Issue by almazini** [rick2785/SideMenu#1]
Hi Rick! 

I am trying to call side menu from my initial home view controller. 

You create an instance of SideMenu in viewDidLoad method and I wonder how it is possible to show sidemenu buy clicking a button on view controller? 

To be more clear: lets say I have a button on my parent view controller and I want to call sidemenu by pressing this button?

Button's action method cant be inside viewdidload() and I cant create an instance of SideMenu class outside viewDidLoad. 

Thanks for you project and help!

**Comment by rick2785** [comment]
Simply pass SideMenuDelegate within your ViewController parameters as seen in the code. This gives you the ability to call the SideMenu class. If you want a button, you can make a empty function and simply call it within viewDidLoad(). You can also search for different examples in stackoverflow. Here's one: http://stackoverflow.com/questions/39815352/stuck-with-adding-target-to-button-in-swift-3-programmatically

**Comment by almazini** [comment]
Sorry don't understand what do you mean by "pass Delegate within your VC"

Yes I know how to create button in ViewDidLoad and call functions outside it. 

I am trying to do opposite thing. Please check my screenshot. 

![screen shot 2017-01-07 at 12 30 52](https://cloud.githubusercontent.com/assets/4295443/21741132/eb192b38-d4d5-11e6-99f6-b74a194744c5.png)

My Button is created in storyboard and connected to ViewController class. 
I am trying to call `sideMenu.toggleMenu(open: true)` by pressing this button.

Thank you for your help

**Comment by rick2785** [comment]
In SideMenu.swift, I'm using UIDynamics to make a drop in component side menu. This sideMenu class inherits from UIView so I can add it anywhere. I also used Delegation for the sideMenu to help trigger the correct functions when a user hits a specific button. Now within the class, you adopt certain protocols to (in my case) display all the elements in a TableView. Then I implemented the delegate functions required by tableViewDelegate and datasource(i.e. numberOfRowsInSection). I then added properties( i.e. backgroundView, menuTable) and I also added a initializer. 

To trigger animations and dynamic behaviors I used gesture recognizers. One recognized a swipe to the right, the other to the left. This particular function is called handleGestures. Swiping to the right opens the menu and you close the menu by swiping to the left. Within toggleMenu, I removed all dynamic behaviors from the animator because this is called every time a user opens the menu. This also means if these behaviors weren't removed, you would have unneeded copies. I then created gravity behaviors for the opening & closing speed, and a boundary for the menu. 

You can command + click the different behaviors to see more details( i.e. UIPushBehavior). To make the buttons more bouncy, I used elasticity. To know which item a user pressed, I used a design pattern called delegation. To incorporate this in sideMenu I created a protocol. The function didSelectMenuItem works with a title and index.  Moving on to ViewController.swift, within viewDidLoad I created an instance of sideMenu. I then adopted the sideMenuDelegate protocol and implemented the necessary function didSelectMenuItem(). 

In this project, I used UIGestures to open and close the Menu. If you're looking to make a button with the same functionality, my current code wouldn't work.
